###Issue
POST http://localhost:8080/email-auth/issue
Content-Type: application/json

{
  "email": "test2@test.com"
}

###Validate
POST http://localhost:8080/email-auth/validate
Content-Type: application/json

{
  "email": "test2@test.com",
  "code": "IexgP"
}
