###Create
POST http://localhost:8080/recruitment-process
Content-Type: application/json

{
  "recruitmentId": "1",
  "userId": "2",
  "resumeId": "1"
}

###InProgress
POST http://localhost:8080/recruitment-process/in-progress
Content-Type: application/json

{
  "recruitmentProcessId": "1",
  "teamId": "1",
  "leaderId": "1"
}

###Pass
POST http://localhost:8080/recruitment-process/pass
Content-Type: application/json

{
  "recruitmentProcessId": "",
  "teamId": "",
  "leaderId": ""
}

###Cancel
POST http://localhost:8080/recruitment-process/cancel
Content-Type: application/json

{
  "recruitmentProcessId": "",
  "teamId": "",
  "userId": ""
}

###Fail
POST http://localhost:8080/recruitment-process/fail
Content-Type: application/json

{
  "recruitmentProcessId": "",
  "teamId": "",
  "leaderId": ""
}

###getMyRecruitmentProcessList
GET http://localhost:8080/recruitment-process/getMyRecruitmentProcessList
Content-Type: application/json

{
  "searchType" : "ALL",
  "searchName" : "",
  "page" : 0,
  "size" : 10,
  "userId": "2"
}

###getMyRecruitmentProces
GET http://localhost:8080/recruitment-process/getMyRecruitmentProcess
Content-Type: application/json

{
  "userId": "2"
}