###Create
POST http://localhost:8080/recruitment
Content-Type: application/json

{
  "userId": "1",
  "teamId": "1",
  "title": "test",
  "content": "test"
}

###Update
POST http://localhost:8080/recruitment/update
Content-Type: application/json

{
  "recruitmentId": "",
  "userId": "",
  "teamId": "",
  "title": "",
  "content": ""
}

###Inactivate
POST http://localhost:8080/recruitment/inactivate
Content-Type: application/json

{
  "recruitmentId": "",
  "userId": "",
  "teamId": ""
}

###Activate
POST http://localhost:8080/recruitment/activate
Content-Type: application/json

{
  "recruitmentId": "1",
  "userId": "1",
  "teamId": "1",
  "closedAt": "2023-03-06T23:00:00.0000"
}

###Delete
POST http://localhost:8080/recruitment/delete
Content-Type: application/json

{
  "recruitmentId": "",
  "userId": "",
  "teamId": ""
}

###ClosedAtExtend
POST http://localhost:8080/recruitment/closedAtExtend
Content-Type: application/json

{
  "recruitmentId": "",
  "userId": "",
  "teamId": "",
  "closedAt": "2022-10-07T23:10:00.0000"
}

###GetMyRecruitment
GET http://localhost:8080/recruitment/getMyRecruitment
Content-Type: application/json

{
  "teamId": "1"
}