###Create
POST http://localhost:8080/team
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNQ0ogVXNlciBBQ0NFU1MgQXBpIFRva2VuIiwiaXNzIjoiTUNKIiwiaWF0IjoxNjc5MjEwNTgzLCJqdGkiOiIxIiwiYXVkIjoidGVzdDFAdGVzdC5jb20iLCJleHAiOjE2NzkyMTA3NjN9.bz1W0MhU8myyCo2oT1xxcrbeLRBpFeHB7TcjyIOD_Jk
Content-Type: application/json

{
  "name": "test1",
  "description": "test",
  "memberNum": "18"
}

###Update
POST http://localhost:8080/team/update
Content-Type: application/json

{
  "teamId": "",
  "userId": "",
  "name": "",
  "description": "",
  "logo": "",
  "memberNum": ""
}

###Activate
POST http://localhost:8080/team/activate
Content-Type: application/json

{
  "teamId": "",
  "userId": ""
}

###Inactivate
POST http://localhost:8080/team/inactivate
Content-Type: application/json

{
  "teamId": "",
  "userId": ""
}

###GetMyTeam
GET http://localhost:8080/team/getMyTeam
Content-Type: application/json

{
  "teamId": "1"
}

###GetMyTeamList
GET http://localhost:8080/team/getMyTeamList
Content-Type: application/json

{
  "searchType" : "ALL",
  "searchName" : "",
  "page" : 0,
  "size" : 10,
  "userId": "1"
}