###Create
POST http://localhost:8080/user
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test",
  "nickname": "test",
  "interest": "test",
  "age": "18"
}

###ChagneInformation
POST http://localhost:8080/user/change-information
Content-Type: application/json

{
  "userId": "",
  "nickname": "",
  "interest": "",
  "age": ""
}

###ChangePassword
POST http://localhost:8080/user/change-password
Content-Type: application/json

{
  "userId": "",
  "password": "",
  "newPassword": ""
}

###Activate
POST http://localhost:8080/user/activate
Content-Type: application/json

{
  "userId": ""
}

###Inactivate
POST http://localhost:8080/user/inactivate
Content-Type: application/json

{
  "userId": ""
}

###GetInformation
GET http://localhost:8080/user/get-information
Content-Type: application/json

{
  "userId": "1"
}

